packages:
  - 'apps/*'
  - 'libs/*'
  - 'libs/shared/*'

autoInstallPeers: true
allowBuilds:
  '@scarf/scarf': set this to true or false
  nx: true
  unrs-resolver: set this to true or false
minimumReleaseAgeExclude:
  - '@nx/devkit@23.0.0'
  - '@nx/docker@23.0.0'
  - '@nx/eslint@23.0.0'
  - '@nx/jest@23.0.0'
  - '@nx/js@23.0.0'
  - '@nx/nest@23.0.0'
  - '@nx/node@23.0.0'
  - '@nx/nx-darwin-arm64@23.0.0'
  - '@nx/nx-darwin-x64@23.0.0'
  - '@nx/nx-freebsd-x64@23.0.0'
  - '@nx/nx-linux-arm-gnueabihf@23.0.0'
  - '@nx/nx-linux-arm64-gnu@23.0.0'
  - '@nx/nx-linux-arm64-musl@23.0.0'
  - '@nx/nx-linux-x64-gnu@23.0.0'
  - '@nx/nx-linux-x64-musl@23.0.0'
  - '@nx/nx-win32-arm64-msvc@23.0.0'
  - '@nx/nx-win32-x64-msvc@23.0.0'
  - '@nx/workspace@23.0.0'
  - nx@23.0.0
